# -*- coding: utf-8 -*-
"""Punto_8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

# **Octavo Punto**

**Enunciado:** Para el punto anterior incluir las funciones en un archivo independiente e importarlas para su uso.
"""

from funciones_punto_7 import CalcularPromedio
from funciones_punto_7 import CalcularMediana
from funciones_punto_7 import CalcularPromedioMultiplicativo
from funciones_punto_7 import OrdenarAscendente
from funciones_punto_7 import OrdenarDescendente
from funciones_punto_7 import CalcularPoteniaMayor
from funciones_punto_7 import CalcularRaizCubica

if __name__ == "__main__":
  a = float(input("Ingrese el primer numero:"))
  b = float(input("Ingrese el segundo numero:"))
  c = float(input("Ingrese el tercer numero:"))
  d = float(input("Ingrese el cuarto numero:"))
  e = float(input("Ingrese el quinto numero:"))
  promedio_f = CalcularPromedio(a, b, c, d, e)
  mediana_f = CalcularMediana(a, b, c, d, e)
  promediomultiplicativo_f = CalcularPromedioMultiplicativo(a, b, c, d, e)
  ascendente_f = OrdenarAscendente(a, b, c, d, e)
  descendente_f = OrdenarDescendente(a, b, c, d, e)
  potencia_f = CalcularPoteniaMayor(a, b, c, d, e)
  raizc_f = CalcularRaizCubica(a, b, c, d, e)
  print("----------------------------------------------------------------")
  print("El promedio es " + str(promedio_f))
  print("----------------------------------------------------------------")
  print("La mediana es " + str(mediana_f))
  print("----------------------------------------------------------------")
  print("El promedio multiplicativo es " + str(promediomultiplicativo_f))
  print("----------------------------------------------------------------")
  print("El orden ascencente es " + str(ascendente_f))
  print("----------------------------------------------------------------")
  print("El orden descedente es " + str(descendente_f))
  print("----------------------------------------------------------------")
  print("La potencia del mayor número elevado al menor número es " + str(potencia_f))
  print("----------------------------------------------------------------")
  print("La raíz cúbica de menor número es " + str(raizc_f))