# -*- coding: utf-8 -*-
"""Punto_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

# **Primer Punto**

**Enunciado:** Dado la figura de la imagen, desarrolle:

- Una función matemática para calcular el volumen y el área superficial.
- Cree dos funciones en python para calcular los valores antes establecidos, al ingresar por teclado r1, r2 y h.
- Revise como utilizar el valor de pi usando import math y math.pi
"""

import math as m
p=m.pi

def CalcularVolumen(r1:float, r2:float, h:float) -> float:
  vol = ((4*p*(r1**3))/3) + (((p*(r2**2)*h))/3)
  return vol

def CalcularAreaSuperficial(r1:float, r2:float, h:float) -> float:
  asup = (4*p*(r1**2)) + (p*r2*(m.sqrt((r2**2)+(h**2))))
  return asup

def Calcularr1(r1:float) -> float:
  vol_esf = ((4*p*(r1**3))/3)
  r1c = ((3*vol_esf)/(4*p))**(1/3)
  return r1c

def CalcularR2yh(r2:float, h:float) -> float:
  vol_cono = (((p*(r2**2)*h))/3)
  r2c = m.sqrt((3*vol_cono)/(p*h))
  hc = ((3*vol_cono)/(p*(r2**2)))
  return r2c, hc

if __name__ == "__main__":
  r1 = float(input("Ingrese radio 1 de la esfera:"))
  r2 = float(input("Ingrese radio 2 del cono:"))
  h = float(input("Ingrese altura del cono:"))
  vol_total = CalcularVolumen(r1, r1, h)
  asup_total = CalcularAreaSuperficial(r1, r1, h)
  r1cal = Calcularr1(r1)
  r2yhcal = CalcularR2yh(r2, h)
  print("----------------------------------------------------------------")
  print("El volumen total es " + str(vol_total))
  print("El area superficial total es " + str(asup_total))
  print("----------------------------------------------------------------")
  print("El valor del radio de la esfera es " + str(r1cal))
  print("El valor de radio del cono y su altura es " + str(r2yhcal))