# -*- coding: utf-8 -*-
"""Punto_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

# **Segundo Punto**

**Enunciado:** Dado la figura de la imagen, desarrolle:
- Una función matemática para calcular el área y el perimetro.
- Cree dos funciones en python para calcular los valores antes establecidos, al ingresar por teclado r, a y b.
- Revise como utilizar el valor de pi usando import math y math.pi
"""

import math as m
p=m.pi

def CalcularArea(r:float, a:float, b:float) -> float:
  area = (2*(p*(r**2))) + (b*a)
  return area

def CalcularPerimetro(r:float, a:float, b:float) -> float:
  perimetro = (2*p*r) + (2*(b+a))
  return perimetro

def Calcularr(r:float) -> float:
  area_circulo = (p*(r**2))
  rc = m.sqrt(area_circulo/p)
  return rc

def CalcularAyB(a:float, b:float) -> float:
  area_rect = (b*a)
  a = area_rect/b
  b = area_rect/a
  return a, b

if __name__ == "__main__":
  r = float(input("Ingrese radio de los circulos:"))
  a = float(input("Ingrese la altura del rectangulo:"))
  b = float(input("Ingrese la base del rectangulo:"))
  area_total = CalcularArea(r, a, b)
  perimetro_total = CalcularPerimetro(r, a, b)
  rcal = Calcularr(r)
  AyBcal = CalcularAyB(a, b)
  print("----------------------------------------------------------------")
  print("El area total es " + str(area_total))
  print("El perimetro total es " + str(perimetro_total))
  print("----------------------------------------------------------------")
  print("El valor del radio de la esfera es " + str(rcal))
  print("El valor de radio del cono y su altura es " + str(AyBcal))